# Project information
name: tomodomoco
repo: git://github.com/TomodomoCo/tomodomoco-site.git

uploads:
  - public/assets
  - public/content/plugins/tomodomo-block-columns/build
  - public/content/plugins/tomodomo-block-logo-grid/build

# Deploy alerts
alerts:
  slack:
    channel: 'activity'
    webhook: 'https://hooks.slack.com/services/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'

# Deployment stages
stage:
  dev:
    ip: 10.1.1.17
    ports:
      ssh: 22
    user: vagrant
    domain: dev.tomodomo.co
  staging:
    ip: 192.241.190.154
    ports:
      ssh: 22
    user: staging
    branch: staging
    domain: staging.tomodomo.co
    deploy_to: /srv/users/staging/apps/tomodomo-staging/deploy
  production:
    ip: 192.241.190.154
    ports:
      ssh: 22
    user: production
    branch: production
    domain: tomodomo.co
    deploy_to: /srv/users/production/apps/tomodomo-production/deploy
