# Project information
name: tomodomoco
repo: git://github.com/TomodomoCo/tomodomoco-site.git

uploads:
  - public/assets
  - public/content/plugins/tomodomo-block-columns/build

# Deploy alerts
alerts:
  slack:
    channel: 'activity'
    webhook: 'https://hooks.slack.com/services/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'

# Deployment stages
stage:
  dev:
    ip: 10.1.1.17
    ports:
      ssh: 22
    user: vagrant
    domain: dev.tomodomo.co
  staging:
    ip: 0.0.0.0
    ports:
      ssh: 22
    user: deploy
    branch: master
    domain: staging.tomodomo.co
  production:
    ip: 0.0.0.0
    ports:
      ssh: 22
    user: deploy
    branch: master
    domain: tomodomo.co
